# Generated by Django 3.2.5 on 2023-01-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('category', models.CharField(max_length=15)),
                ('img_url', models.TextField(null=True)),
                ('description', models.TextField()),
                ('starting_bid', models.FloatField()),
                ('current_amt', models.FloatField()),
                ('bid_status', models.CharField(max_length=10)),
                ('created_by', models.CharField(max_length=25)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
