# Generated by Django 3.2.5 on 2023-01-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bid_status',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='current_amt',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='starting_bid',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
